import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface ReportData {
  workOrder: {
    wo_number: string;
    product_type: string;
    batch_size: number;
    status: string;
    created_at: string;
    completed_at: string | null;
    start_date: string | null;
    shipping_date: string | null;
    customer_name: string | null;
  };
  items: Array<{
    serial_number: string;
    status: string;
    completed_at: string | null;
    label_printed: boolean;
    label_printed_at: string | null;
    label_printed_by_name?: string;
  }>;
  stepExecutions: Array<{
    step_number: number;
    step_title: string;
    operator_name: string;
    completed_at: string | null;
    measurement_values: Record<string, unknown>;
    validation_status: string | null;
    serial_number: string;
  }>;
  batchMaterials: Array<{
    material_type: string;
    batch_number: string;
    serial_number: string;
    scanned_at: string;
  }>;
  operators: Array<{
    full_name: string;
    steps_completed: number;
  }>;
  certificates: Array<{
    serial_number: string;
    generated_at: string | null;
    generated_by_name: string | null;
  }>;
  checklistResponses: Array<{
    serial_number: string;
    item_text: string;
    checked: boolean;
    checked_by_name: string | null;
  }>;
}

interface ExportOptions {
  language: 'en' | 'nl';
}

const translations = {
  en: {
    productionReport: 'Production Report',
    generatedOn: 'Generated on',
    workOrderDetails: 'Work Order Details',
    workOrder: 'Work Order',
    customer: 'Customer',
    status: 'Status',
    batchSize: 'Batch Size',
    created: 'Created',
    started: 'Started',
    shipping: 'Shipping',
    completed: 'Completed',
    summaryStatistics: 'Summary Statistics',
    itemsCompleted: 'Items Completed',
    passedValidations: 'Passed Validations',
    failedValidations: 'Failed Validations',
    certificatesIssued: 'Certificates Issued',
    labelsPrinted: 'Labels Printed',
    operatorsInvolved: 'Operators Involved',
    productionSteps: 'Production Steps',
    step: 'Step',
    serialNumber: 'Serial Number',
    operator: 'Operator',
    validation: 'Validation',
    measurements: 'Measurements',
    batchMaterials: 'Batch Materials',
    materialType: 'Material Type',
    batchNumber: 'Batch Number',
    scannedAt: 'Scanned At',
    qualityCertificates: 'Quality Certificates',
    generatedBy: 'Generated By',
    checklistResponses: 'Checklist Responses',
    checkedBy: 'Checked By',
    passed: 'PASSED',
    failed: 'FAILED',
    pending: 'PENDING',
    checked: 'Checked',
    unchecked: 'Unchecked',
    operators: 'Operators',
    stepsCompleted: 'steps completed',
    notAvailable: 'N/A',
  },
  nl: {
    productionReport: 'Productierapport',
    generatedOn: 'Gegenereerd op',
    workOrderDetails: 'Werkorderdetails',
    workOrder: 'Werkorder',
    customer: 'Klant',
    status: 'Status',
    batchSize: 'Batchgrootte',
    created: 'Aangemaakt',
    started: 'Gestart',
    shipping: 'Verzending',
    completed: 'Voltooid',
    summaryStatistics: 'Samenvatting Statistieken',
    itemsCompleted: 'Items Voltooid',
    passedValidations: 'Geslaagde Validaties',
    failedValidations: 'Mislukte Validaties',
    certificatesIssued: 'Certificaten Uitgegeven',
    labelsPrinted: 'Labels Afgedrukt',
    operatorsInvolved: 'Betrokken Operators',
    productionSteps: 'Productiestappen',
    step: 'Stap',
    serialNumber: 'Serienummer',
    operator: 'Operator',
    validation: 'Validatie',
    measurements: 'Metingen',
    batchMaterials: 'Batch Materialen',
    materialType: 'Materiaaltype',
    batchNumber: 'Batchnummer',
    scannedAt: 'Gescand Op',
    qualityCertificates: 'Kwaliteitscertificaten',
    generatedBy: 'Gegenereerd Door',
    checklistResponses: 'Checklist Antwoorden',
    checkedBy: 'Gecontroleerd Door',
    passed: 'GESLAAGD',
    failed: 'MISLUKT',
    pending: 'IN AFWACHTING',
    checked: 'Gecontroleerd',
    unchecked: 'Niet Gecontroleerd',
    operators: 'Operators',
    stepsCompleted: 'stappen voltooid',
    notAvailable: 'N.v.t.',
  },
};

export const generateProductionReportPdf = async (
  data: ReportData,
  options: ExportOptions
): Promise<void> => {
  const t = translations[options.language];
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const formatDateStr = (dateStr: string | null) => {
    if (!dateStr) return t.notAvailable;
    try {
      return format(new Date(dateStr), 'dd MMM yyyy HH:mm');
    } catch {
      return dateStr;
    }
  };

  const addNewPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      y = margin;
      return true;
    }
    return false;
  };

  const drawSectionHeader = (title: string) => {
    addNewPageIfNeeded(15);
    pdf.setFillColor(240, 240, 240);
    pdf.rect(margin, y, contentWidth, 8, 'F');
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(50, 50, 50);
    pdf.text(title, margin + 3, y + 5.5);
    y += 12;
  };

  const drawKeyValue = (key: string, value: string, xOffset = 0) => {
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text(key, margin + xOffset, y);
    pdf.setTextColor(30, 30, 30);
    pdf.setFont('helvetica', 'bold');
    pdf.text(value, margin + xOffset + 35, y);
  };

  // Header
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text(t.productionReport, margin, y);
  y += 8;

  pdf.setFontSize(14);
  pdf.setTextColor(34, 139, 34); // Green color for WO number
  pdf.text(data.workOrder.wo_number, margin, y);
  y += 6;

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${t.generatedOn}: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, margin, y);
  y += 10;

  // Horizontal line
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Work Order Details
  drawSectionHeader(t.workOrderDetails);

  const col1X = 0;
  const col2X = contentWidth / 2;

  drawKeyValue(t.customer + ':', data.workOrder.customer_name || t.notAvailable, col1X);
  drawKeyValue(t.status + ':', data.workOrder.status.toUpperCase(), col2X);
  y += 6;

  drawKeyValue(t.batchSize + ':', String(data.workOrder.batch_size), col1X);
  drawKeyValue(t.created + ':', formatDateStr(data.workOrder.created_at), col2X);
  y += 6;

  drawKeyValue(t.started + ':', formatDateStr(data.workOrder.start_date), col1X);
  drawKeyValue(t.shipping + ':', formatDateStr(data.workOrder.shipping_date), col2X);
  y += 6;

  drawKeyValue(t.completed + ':', formatDateStr(data.workOrder.completed_at), col1X);
  y += 10;

  // Summary Statistics
  const completedItems = data.items.filter(i => i.status === 'completed').length;
  const passedValidations = data.stepExecutions.filter(e => e.validation_status === 'passed').length;
  const failedValidations = data.stepExecutions.filter(e => e.validation_status === 'failed').length;
  const labelsPrinted = data.items.filter(i => i.label_printed).length;

  drawSectionHeader(t.summaryStatistics);

  const statWidth = contentWidth / 3;
  pdf.setFontSize(9);

  // Row 1
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text(t.itemsCompleted, margin, y);
  pdf.text(t.passedValidations, margin + statWidth, y);
  pdf.text(t.failedValidations, margin + statWidth * 2, y);
  y += 5;

  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text(`${completedItems}/${data.items.length}`, margin, y);
  pdf.setTextColor(34, 139, 34);
  pdf.text(String(passedValidations), margin + statWidth, y);
  pdf.setTextColor(220, 53, 69);
  pdf.text(String(failedValidations), margin + statWidth * 2, y);
  y += 8;

  // Row 2
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text(t.certificatesIssued, margin, y);
  pdf.text(t.labelsPrinted, margin + statWidth, y);
  pdf.text(t.operatorsInvolved, margin + statWidth * 2, y);
  y += 5;

  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text(String(data.certificates.length), margin, y);
  pdf.text(`${labelsPrinted}/${data.items.length}`, margin + statWidth, y);
  pdf.text(String(data.operators.length), margin + statWidth * 2, y);
  y += 12;

  // Production Steps
  if (data.stepExecutions.length > 0) {
    drawSectionHeader(t.productionSteps);

    // Table header
    const colWidths = [35, 55, 35, 25, 30];
    pdf.setFillColor(245, 245, 245);
    pdf.rect(margin, y - 2, contentWidth, 6, 'F');
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(80, 80, 80);

    let xPos = margin;
    pdf.text(t.serialNumber, xPos, y + 2);
    xPos += colWidths[0];
    pdf.text(t.step, xPos, y + 2);
    xPos += colWidths[1];
    pdf.text(t.operator, xPos, y + 2);
    xPos += colWidths[2];
    pdf.text(t.validation, xPos, y + 2);
    y += 8;

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(50, 50, 50);

    for (const exec of data.stepExecutions.slice(0, 30)) { // Limit to 30 for PDF size
      addNewPageIfNeeded(12);

      xPos = margin;
      pdf.setFontSize(7);
      pdf.text(exec.serial_number.slice(0, 18), xPos, y);
      xPos += colWidths[0];
      pdf.text(`${exec.step_number}: ${exec.step_title.slice(0, 25)}`, xPos, y);
      xPos += colWidths[1];
      pdf.text(exec.operator_name.slice(0, 15), xPos, y);
      xPos += colWidths[2];

      if (exec.validation_status === 'passed') {
        pdf.setTextColor(34, 139, 34);
        pdf.text(t.passed, xPos, y);
      } else if (exec.validation_status === 'failed') {
        pdf.setTextColor(220, 53, 69);
        pdf.text(t.failed, xPos, y);
      } else {
        pdf.setTextColor(100, 100, 100);
        pdf.text(t.pending, xPos, y);
      }
      pdf.setTextColor(50, 50, 50);

      y += 5;

      // Measurements
      if (Object.keys(exec.measurement_values).length > 0) {
        pdf.setFontSize(6);
        pdf.setTextColor(80, 80, 80);
        const measurements = Object.entries(exec.measurement_values)
          .map(([k, v]) => `${k}: ${v}`)
          .join(' | ');
        pdf.text(`  ${t.measurements}: ${measurements.slice(0, 80)}`, margin, y);
        y += 4;
        pdf.setTextColor(50, 50, 50);
      }
    }

    if (data.stepExecutions.length > 30) {
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`... and ${data.stepExecutions.length - 30} more steps`, margin, y);
      y += 6;
    }

    y += 6;
  }

  // Batch Materials
  if (data.batchMaterials.length > 0) {
    drawSectionHeader(t.batchMaterials);

    pdf.setFontSize(7);
    for (const mat of data.batchMaterials.slice(0, 20)) {
      addNewPageIfNeeded(6);
      pdf.setTextColor(50, 50, 50);
      pdf.text(`${mat.serial_number} | ${mat.material_type}: ${mat.batch_number} | ${formatDateStr(mat.scanned_at)}`, margin, y);
      y += 4;
    }

    if (data.batchMaterials.length > 20) {
      pdf.setTextColor(100, 100, 100);
      pdf.text(`... and ${data.batchMaterials.length - 20} more materials`, margin, y);
      y += 4;
    }

    y += 6;
  }

  // Certificates
  if (data.certificates.length > 0) {
    drawSectionHeader(t.qualityCertificates);

    pdf.setFontSize(8);
    for (const cert of data.certificates) {
      addNewPageIfNeeded(6);
      pdf.setTextColor(50, 50, 50);
      const certInfo = `${cert.serial_number} | ${t.generatedBy}: ${cert.generated_by_name || t.notAvailable} | ${formatDateStr(cert.generated_at)}`;
      pdf.text(certInfo, margin, y);
      y += 5;
    }

    y += 6;
  }

  // Operators
  if (data.operators.length > 0) {
    drawSectionHeader(t.operators);

    pdf.setFontSize(8);
    for (const op of data.operators) {
      addNewPageIfNeeded(6);
      pdf.setTextColor(50, 50, 50);
      pdf.text(`${op.full_name} - ${op.steps_completed} ${t.stepsCompleted}`, margin, y);
      y += 5;
    }

    y += 6;
  }

  // Footer on each page
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `${data.workOrder.wo_number} | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save
  pdf.save(`${data.workOrder.wo_number}_production_report.pdf`);
};
